#!/bin/bash

ps aux | awk '{if ($6 != 0) print $2" "$6" "$11}' | sort -nk1 | tail -n +2 | head -n -6 > temp
sleep 60
ps aux | awk '{if ($6 != 0) print $2" "$6" "$11}' | sort -mk1 | tail -n +2 | head -n -6 > temp2
cat temp |
while read a
do
pid=$(awk '{print $1}' <<< $a)
mem1=$(awk '{print $2}' <<< $a)
cmd=$(awk '{print $3}' <<< $a)
mem2=$(cat temp2 | awk -v id="$pid" '{if ($1==id) print $2}')
let "mem = mem2 - men1"
echo $pid":"$cmd":"$mem
done | sort -nrk3 | head -3
rm -f temp
rm -f temp2