#!/bin/bash

ps aux | awk '{printf $2" "$6" "$11"\n"}' | sort -nk 1 | tail -n +2 | head -n -6 > buffer1

sleep 60

ps aux | awk '{printf $2" "$6" "$11"\n"}' | sort -nk 1 | tail -n +2 | head -n -6 > buffer2

cat buffer1 | while read line
do

    pspid=echo"$line | awk '{printf $1"\n"}'"
    firstmemory=echo"$line | awk '{printf $2"\n"}'"
    secondmemory=echo"buffer2 | awk -v id="$pspid" '{printf $2"\n"}'"
    command=echo"$line | awk '{printf $3"\n"}'"
    totalmemory=($secondmemory - $firstmemory)
    echo -e "$pspid" : "$command" : "$totalmemory"

done | sort -nrk 3 | head -3

rm -f buffer1
rm -f buffer2
