#!/bin/bash

directorywithbackup=$(find /home/user -name "Backup-[0-9]*-[0-9]*-[0-9]*" -type d -ctime -7)

ls -1 $directorywithbackup | while read -r file
 do
    if ! [[ $file =~ .*\.[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]
    then
        cp -a $directorywithbackup/"$file" /home/user/source/"$file" 2>/dev/null
    fi
done